@tool
extends RefCounted

## The droppable-component catalog for the CYBER SUNDAY editor tools (the palette dock + item placer read it).
## One row per drop-in component a designer attaches in the editor. Generated from the plugin discovery pass;
## a GUT test pins the count and asserts every script_path / scene_path resolves on disk.

const COMPONENTS: Array[Dictionary] = [
	{
		"class_name": "CanPickUp",
		"script_path": "res://scripts/components/can_pick_up.gd",
		"scene_path": "res://scenes/components/can_pick_up.tscn",
		"extends": "LookAtInteractable",
		"category": "World Objects",
		"add_mode": "instance",
		"description": "Aim+E pickup that adds a configured Item (or rolled loot) to the player's backpack; builds its own world visual when asked.",
		"key_exports": ["item", "amount", "item_stacks", "loot_table", "build_model_from_item"],
	},
	{
		"class_name": "Pettable",
		"script_path": "res://scripts/components/pettable.gd",
		"scene_path": "",
		"extends": "Area3D",
		"category": "World Objects",
		"add_mode": "child",
		"description": "Drop on any object so the player can HOLD the Takedown key (Q) aimed at it to pet it — a heart floats up. Auto-fits its own hitbox at runtime; fires petted(by).",
		"key_exports": ["enabled", "hold_time", "max_range", "display_name", "heart_color"],
	},
	{
		"class_name": "MoneyPickUp",
		"script_path": "res://scripts/components/money_pickup.gd",
		"scene_path": "res://scenes/components/money_pickup.tscn",
		"extends": "LookAtInteractable",
		"category": "World Objects",
		"add_mode": "instance",
		"description": "A stash of zorkmids; collects amount, toasts, frees itself, builds a default gold coin if no body is authored.",
		"key_exports": ["amount", "pickup_label", "world_model"],
	},
	{
		"class_name": "UpgradePickup",
		"script_path": "res://scripts/components/upgrade_pickup.gd",
		"scene_path": "res://scenes/components/upgrade_pickup.tscn",
		"extends": "LookAtInteractable",
		"category": "Player",
		"add_mode": "instance",
		"description": "Aim+E to permanently grant a player Ability (drag an ability scene into grants); builds a glowing emblem.",
		"key_exports": ["grants", "unlock_id", "display_name", "world_model", "toast_color"],
	},
	{
		"class_name": "ItemContainer",
		"script_path": "res://scripts/components/container.gd",
		"scene_path": "res://scenes/components/container.tscn",
		"extends": "LookAtInteractable",
		"category": "World Objects",
		"add_mode": "instance",
		"description": "A persistent lootable crate/chest/locker with two-way transfer; child a Lock to keep it shut.",
		"key_exports": ["item_stacks", "money", "loot_table", "container_name"],
	},
	{
		"class_name": "LootableCorpse",
		"script_path": "res://scripts/components/lootable_corpse.gd",
		"scene_path": "",
		"extends": "LookAtInteractable",
		"category": "World Objects",
		"add_mode": "child",
		"description": "A dead body's loot hitbox that opens the loot screen; usually spawned by the death system, rarely hand-placed.",
		"key_exports": ["trigger_radius"],
	},
	{
		"class_name": "Merchant",
		"script_path": "res://scripts/components/merchant.gd",
		"scene_path": "res://scenes/components/merchant.tscn",
		"extends": "LookAtInteractable",
		"category": "World Objects",
		"add_mode": "instance",
		"description": "A shop; standalone (aim+E opens it) or data-only on a dialogue NPC. Stocks StockEntry rows, has a till and buy/sell mults.",
		"key_exports": ["stock_counts", "shop_name", "money", "buy_mult", "sell_mult"],
	},
	{
		"class_name": "Restocker",
		"script_path": "res://scripts/components/restocker.gd",
		"scene_path": "",
		"extends": "Node",
		"category": "World Objects",
		"add_mode": "child",
		"description": "Drop under a Merchant/ItemContainer to top it back to its authored baseline over time or on the player's next visit.",
		"key_exports": ["mode", "interval", "target_path"],
	},
	{
		"class_name": "Healer",
		"script_path": "res://scripts/components/healer.gd",
		"scene_path": "res://scenes/components/healer.tscn",
		"extends": "LookAtInteractable",
		"category": "World Objects",
		"add_mode": "instance",
		"description": "Pay to restore HP-to-full and clear limb damage; standalone or data-only on a dialogue NPC.",
		"key_exports": ["heal_name", "cost_per_hp", "min_cost", "standalone"],
	},
	{
		"class_name": "Bonfire",
		"script_path": "res://scripts/components/bonfire.gd",
		"scene_path": "res://scenes/components/bonfire.tscn",
		"extends": "LookAtInteractable",
		"category": "World Objects",
		"add_mode": "instance",
		"description": "Rest/checkpoint station: full heal + set respawn point; standalone or data-only on a dialogue NPC.",
		"key_exports": ["bonfire_name", "standalone"],
	},
	{
		"class_name": "LevelUp",
		"script_path": "res://scripts/components/level_up.gd",
		"scene_path": "res://scenes/components/levelup.tscn",
		"extends": "LookAtInteractable",
		"category": "Player",
		"add_mode": "instance",
		"description": "Spend zorkmids to raise a CharacterStat and/or spend XP skill points on perks (picker on when available_perks set).",
		"key_exports": ["station_name", "base_cost", "cost_per_level", "available_perks", "perk_points_per_level"],
	},
	{
		"class_name": "PerkStation",
		"script_path": "res://scripts/components/perk_station.gd",
		"scene_path": "",
		"extends": "LookAtInteractable",
		"category": "Player",
		"add_mode": "child",
		"description": "Aim+E at a shrine to learn a Perk (permanent stat bonuses / ability grant); optionally consumed on use.",
		"key_exports": ["perk", "consume_on_use"],
	},
	{
		"class_name": "RespecStation",
		"script_path": "res://scripts/components/respec_station.gd",
		"scene_path": "",
		"extends": "LookAtInteractable",
		"category": "Player",
		"add_mode": "child",
		"description": "Aim+E and pay respec_cost to reverse every unlocked perk and refund its skill point; not consumed.",
		"key_exports": ["station_name", "respec_cost"],
	},
	{
		"class_name": "QuestStarter",
		"script_path": "res://scripts/components/quest_starter.gd",
		"scene_path": "",
		"extends": "LookAtInteractable",
		"category": "Quests",
		"add_mode": "child",
		"description": "A quest board/giver: aim+E to start a Quest; frees itself once accepted by default.",
		"key_exports": ["quest", "prompt_label", "consume_on_use"],
	},
	{
		"class_name": "Radio",
		"script_path": "res://scripts/components/radio.gd",
		"scene_path": "res://scenes/components/radio.tscn",
		"extends": "LookAtInteractable",
		"category": "Audio",
		"add_mode": "instance",
		"description": "An in-world radio that takes precedence over the combat score (plays through a fight; duck_for_combat flips it back) and ducks for dialogue; cycles a folder of tracks from a spatial player.",
		"key_exports": ["radio_name", "shuffle", "fallback_audio", "audio_player", "duck_for_combat"],
	},
	{
		"class_name": "Talkable",
		"script_path": "res://scripts/components/talkable.gd",
		"scene_path": "res://scenes/dialogue/talkable.tscn",
		"extends": "Area3D",
		"category": "Dialogue",
		"add_mode": "instance",
		"description": "Make anything speakable (villager, terminal, vending machine) without overriding the host's root script.",
		"key_exports": ["dialogue", "dialogue_selector", "voice", "display_name", "turn_to_face"],
	},
	{
		"class_name": "DialogueNPC",
		"script_path": "res://scripts/components/dialogue_npc.gd",
		"scene_path": "res://scenes/components/dialogue_npc.tscn",
		"extends": "Node3D",
		"category": "Dialogue",
		"add_mode": "instance",
		"description": "A talkable where the whole node IS the speaker (script on the root, with a child Area3D as range_area).",
		"key_exports": ["dialogue", "dialogue_selector", "voice", "display_name", "range_area"],
	},
	{
		"class_name": "Door",
		"script_path": "res://scripts/components/door.gd",
		"scene_path": "res://scenes/components/door.tscn",
		"extends": "LookAtInteractable",
		"category": "World Objects",
		"add_mode": "instance",
		"description": "Aim+E to swing a door open/closed; a child blocker body seals the doorway until it opens. Has lock knobs.",
		"key_exports": ["pivot", "open_angle", "open_duration", "locked", "requires_item_id"],
	},
	{
		"class_name": "LevelDoor",
		"script_path": "res://scripts/components/level_door.gd",
		"scene_path": "res://scenes/components/level_door.tscn",
		"extends": "LookAtInteractable",
		"category": "Level",
		"add_mode": "instance",
		"description": "A portal to another level: aim+E travels via GameRoot.load_level and arrives at the matching PlayerSpawn.",
		"key_exports": ["target_level", "entry_id", "prompt_label"],
	},
	{
		"class_name": "PlayerSpawn",
		"script_path": "res://scripts/world/player_spawn.gd",
		"scene_path": "res://scenes/world/PlayerSpawn.tscn",
		"extends": "Marker3D",
		"category": "Level",
		"add_mode": "instance",
		"description": "An arrival point in a level; GameRoot drops the player on the spawn whose entry_id matches the LevelDoor used.",
		"key_exports": ["entry_id"],
	},
	{
		"class_name": "TriggerVolume",
		"script_path": "res://scripts/components/trigger_volume.gd",
		"scene_path": "res://scenes/components/trigger_volume.tscn",
		"extends": "Area3D",
		"category": "Encounters",
		"add_mode": "instance",
		"description": "The keystone when-X-do-Y volume: fires a configurable set of independent actions when a body enters/exits.",
		"key_exports": ["trigger_group", "trigger_once", "set_flag", "start_dialogue", "action"],
	},
	{
		"class_name": "TutorialPrompt",
		"script_path": "res://scripts/components/tutorial_prompt.gd",
		"scene_path": "",
		"extends": "TriggerVolume",
		"category": "Level",
		"add_mode": "child",
		"description": "A one-time tooltip volume that teaches a verb once (remembered via a flag), with live {action} keybind tokens.",
		"key_exports": ["prompt_text", "prompt_color", "seen_flag"],
	},
	{
		"class_name": "Lock",
		"script_path": "res://scripts/components/lock.gd",
		"scene_path": "res://scenes/components/lock.tscn",
		"extends": "Node",
		"category": "World Objects",
		"add_mode": "instance",
		"description": "Drop under any interactable (container or Door); the host checks it before opening. Keyed or lockpick-based.",
		"key_exports": ["locked", "requires_item_id", "consumes_item", "unlock_flag"],
	},
	{
		"class_name": "BuildGate",
		"script_path": "res://scripts/components/build_gate.gd",
		"scene_path": "",
		"extends": "Node",
		"category": "World Objects",
		"add_mode": "child",
		"description": "The build-aware twin of Lock: gates a host's open/fire on player stat/perk/ability/reputation requirements (AND).",
		"key_exports": ["required_stat", "required_value", "required_perk", "required_ability", "required_faction_id"],
	},
	{
		"class_name": "CanDestroy",
		"script_path": "res://scripts/components/can_destroy.gd",
		"scene_path": "res://scenes/components/can_destroy.tscn",
		"extends": "StaticBody3D",
		"category": "World Objects",
		"add_mode": "instance",
		"description": "A body that breaks when shot (any weapon); root of a breakable with a CollisionShape3D + MeshInstance3D.",
		"key_exports": ["max_hp", "destroy_effect", "destroy_sound"],
	},
	{
		"class_name": "SpawnOnDestroy",
		"script_path": "res://scripts/components/spawn_on_destroy.gd",
		"scene_path": "res://scenes/components/spawn_on_destroy.tscn",
		"extends": "Node",
		"category": "World Objects",
		"add_mode": "instance",
		"description": "Drop under a CanDestroy/Throwable to spawn loot into the level when the host breaks; loot_table or fixed scene.",
		"key_exports": ["spawn_scene", "count", "scatter", "loot_table"],
	},
	{
		"class_name": "Throwable",
		"script_path": "res://scripts/components/Throwable.gd",
		"scene_path": "res://scenes/components/throwable.tscn",
		"extends": "RigidBody3D",
		"category": "World Objects",
		"add_mode": "instance",
		"description": "A pick-up-and-throw physics object (a crate); emits destroyed on break so SpawnOnDestroy works on it too.",
		"key_exports": ["data", "impact_sfx", "collision_shape", "mesh_instance", "max_hp"],
	},
	{
		"class_name": "ExplosiveBarrel",
		"script_path": "res://scripts/components/explosive_barrel.gd",
		"scene_path": "",
		"extends": "CanDestroy",
		"category": "World Objects",
		"add_mode": "child",
		"description": "A destructible that detonates a damaging explosion when destroyed; chains to other barrels, credits the shooter.",
		"key_exports": ["blast_force", "blast_radius", "blast_upward_bias", "max_hp", "destroy_effect"],
	},
	{
		"class_name": "HazardZone",
		"script_path": "res://scripts/components/hazard_zone.gd",
		"scene_path": "",
		"extends": "Area3D",
		"category": "World Objects",
		"add_mode": "child",
		"description": "A damage-over-time volume (fire/acid/radiation/gas); ticks HP and optionally a StatusEffect, attributed to no one.",
		"key_exports": ["damage_group", "damage_per_tick", "tick_interval", "on_tick_effect"],
	},
	{
		"class_name": "AlarmPanel",
		"script_path": "res://scripts/components/alarm_panel.gd",
		"scene_path": "",
		"extends": "Node3D",
		"category": "Encounters",
		"add_mode": "child",
		"description": "A one-shot tripwire alarm: fires a reinforcement wave, turns a faction hostile, and optionally sounds a klaxon.",
		"key_exports": ["spawner_path", "alarm_faction_id", "alarm_sound"],
	},
	{
		"class_name": "EncounterSpawner",
		"script_path": "res://scripts/components/encounter_spawner.gd",
		"scene_path": "",
		"extends": "Node3D",
		"category": "Encounters",
		"add_mode": "child",
		"description": "Spawns enemies on cue from SpawnDefinition rows; can attach behaviour scenes under every spawn. No prefab.",
		"key_exports": ["spawn_definitions", "spawn_points", "attach_scenes"],
	},
	{
		"class_name": "WaveManager",
		"script_path": "res://scripts/components/wave_manager.gd",
		"scene_path": "",
		"extends": "Node",
		"category": "Encounters",
		"add_mode": "child",
		"description": "Sequences an EncounterSpawner's definitions as timed waves; fired with action start. No prefab.",
		"key_exports": ["spawner_path", "wave_interval", "auto_start"],
	},
	{
		"class_name": "CutscenePlayer",
		"script_path": "res://scripts/components/cutscene_player.gd",
		"scene_path": "",
		"extends": "Node",
		"category": "Cutscene",
		"add_mode": "child",
		"description": "Runs a Cutscene (camera moves, fades, captions, actor blocking) with player control locked. No prefab.",
		"key_exports": ["cutscene"],
	},
	{
		"class_name": "CutsceneActor",
		"script_path": "res://scripts/components/cutscene_actor.gd",
		"scene_path": "",
		"extends": "Node",
		"category": "Cutscene",
		"add_mode": "child",
		"description": "Drop under an NPC to let a Cutscene stage it (WALK_TO/FACE/PLAY_ANIM) with its AI brain suppressed.",
		"key_exports": ["npc_path", "animation_player_path"],
	},
	{
		"class_name": "InvestigatePoint",
		"script_path": "res://scripts/components/investigate_point.gd",
		"scene_path": "",
		"extends": "Marker3D",
		"category": "Stealth",
		"add_mode": "child",
		"description": "A go-look-here beacon: call trigger() to send NPCs to investigate this marker's position. No prefab.",
		"key_exports": ["npc_path", "radius", "alerted"],
	},
	{
		"class_name": "PatrolPath",
		"script_path": "res://scripts/components/patrol_path.gd",
		"scene_path": "",
		"extends": "Node3D",
		"category": "NPC",
		"add_mode": "child",
		"description": "A level-placed route; its Marker3D/Node3D children are the ordered waypoints. Loop or ping-pong. No prefab.",
		"key_exports": ["loop", "wait_time"],
	},
	{
		"class_name": "PatrolBehavior",
		"script_path": "res://scripts/components/patrol_behavior.gd",
		"scene_path": "",
		"extends": "Node",
		"category": "NPC",
		"add_mode": "child",
		"description": "Drop under an NPC and point patrol_path at a PatrolPath; the NPC walks the beat while idle. No prefab.",
		"key_exports": ["enabled", "patrol_path"],
	},
	{
		"class_name": "ScheduleBehavior",
		"script_path": "res://scripts/components/schedule_behavior.gd",
		"scene_path": "",
		"extends": "Node",
		"category": "NPC",
		"add_mode": "child",
		"description": "Drop under an NPC to follow a daily routine: reads WorldClock phase and walks to that phase's marker. No prefab.",
		"key_exports": ["enabled", "schedule", "arrive_distance"],
	},
	{
		"class_name": "GuardDuty",
		"script_path": "res://scripts/components/guard_duty.gd",
		"scene_path": "",
		"extends": "Node",
		"category": "NPC",
		"add_mode": "child",
		"description": "Drop under an NPC to put it on bodyguard duty: it defends protectee (engages anyone hostile to them). No prefab.",
		"key_exports": ["protectee_path", "protectee_group"],
	},
	{
		"class_name": "BodyModelSwap",
		"script_path": "res://scripts/components/body_model_swap.gd",
		"scene_path": "",
		"extends": "Node3D",
		"category": "NPC",
		"add_mode": "child",
		"description": "Swap an NPC's body/head/arms/legs for your own .glb with a live editor preview and drive its runtime gait.",
		"key_exports": ["body_model", "head_model", "body_model_scale", "casts_shadow", "refresh_preview"],
	},
	{
		"class_name": "NpcHeadLookMount",
		"script_path": "res://scripts/components/npc_head_look_mount.gd",
		"scene_path": "res://scenes/components/npc_head_look_mount.tscn",
		"extends": "Node3D",
		"category": "NPC",
		"add_mode": "instance",
		"description": "FNV-style independent head tracking; drop under the Enemy root so the head turns to its foe/player/noise.",
		"key_exports": ["enabled", "look_range", "max_yaw_deg", "turn_speed", "look_at_player"],
	},
	{
		"class_name": "LocomotionFx",
		"script_path": "res://scripts/components/locomotion_fx.gd",
		"scene_path": "res://scenes/components/locomotion_fx.tscn",
		"extends": "Node",
		"category": "NPC",
		"add_mode": "instance",
		"description": "Footstep SFX + landing thud + dust for any CharacterBody3D; attach to override the auto-built one.",
		"key_exports": ["footstep_sounds", "land_sound", "stride_length", "footstep_volume_db", "min_land_speed"],
	},
	{
		"class_name": "FallScream",
		"script_path": "res://scripts/components/fall_scream.gd",
		"scene_path": "res://scenes/components/fall_scream.tscn",
		"extends": "Node",
		"category": "NPC",
		"add_mode": "instance",
		"description": "Plays a yell after falling for a moment, re-arms on landing; drop under any CharacterBody3D.",
		"key_exports": ["scream", "min_fall_time", "min_fall_speed", "volume_db"],
	},
	{
		"class_name": "SelfHealer",
		"script_path": "res://scripts/components/self_healer.gd",
		"scene_path": "res://scenes/components/self_healer.tscn",
		"extends": "Node",
		"category": "NPC",
		"add_mode": "instance",
		"description": "Drop under an NPC so it heals itself back up once its HP fraction drops below a threshold, on a cooldown.",
		"key_exports": ["enabled", "heal_at_hp_frac", "cooldown_ms"],
	},
	{
		"class_name": "PanicOnDamage",
		"script_path": "res://scripts/components/panic_on_damage.gd",
		"scene_path": "res://scenes/components/panic_on_damage.tscn",
		"extends": "Node",
		"category": "NPC",
		"add_mode": "instance",
		"description": "Drop under an NPC to make it flee/panic when hurt (a civilian reaction), scaled by panic_scale.",
		"key_exports": ["enabled", "panic_scale"],
	},
	{
		"class_name": "ProvokeOnAttack",
		"script_path": "res://scripts/components/provoke_on_attack.gd",
		"scene_path": "",
		"extends": "Node",
		"category": "NPC",
		"add_mode": "child",
		"description": "Drop under an NPC so attacking it provokes a hostile response/faction turn.",
		"key_exports": ["enabled"],
	},
	{
		"class_name": "DetectionStinger",
		"script_path": "res://scripts/components/detection_stinger.gd",
		"scene_path": "",
		"extends": "Node",
		"category": "Stealth",
		"add_mode": "child",
		"description": "Drop under an NPC to play a one-shot 'spotted you' audio/visual sting on detection, with a cooldown.",
		"key_exports": ["cooldown"],
	},
	{
		"class_name": "NoiseSource",
		"script_path": "res://scripts/components/noise_source.gd",
		"scene_path": "res://scenes/components/noise_source.tscn",
		"extends": "Node3D",
		"category": "Stealth",
		"add_mode": "instance",
		"description": "A point of sound NPCs can hear and investigate (the stealth distraction channel); persistent or self-freeing one-shot.",
		"key_exports": ["radius", "decay", "lifetime"],
	},
	{
		"class_name": "ShadowVolume",
		"script_path": "res://scripts/components/shadow_volume.gd",
		"scene_path": "",
		"extends": "Area3D",
		"category": "Stealth",
		"add_mode": "child",
		"description": "Paint over a dark region so the player inside reads as unlit to enemy Perception; designer-painted stealth shadow.",
		"key_exports": ["trigger_group"],
	},
	{
		"class_name": "PlayerLightLevel",
		"script_path": "res://scripts/player/player_light_level.gd",
		"scene_path": "",
		"extends": "Node3D",
		"category": "Stealth",
		"add_mode": "child",
		"description": "Drop under the player: samples nearby lights each tick and writes the player's light_exposure for stealth detection.",
		"key_exports": ["host", "ambient", "sample_interval", "require_los"],
	},
	{
		"class_name": "WorldMarker",
		"script_path": "res://scripts/components/world_marker.gd",
		"scene_path": "",
		"extends": "Node3D",
		"category": "Level",
		"add_mode": "child",
		"description": "A point-of-interest beacon that shows as a chevron on the Compass and a dot on the Minimap.",
		"key_exports": ["on_compass", "on_minimap", "color"],
	},
	{
		"class_name": "QuestMarkerSync",
		"script_path": "res://scripts/components/quest_marker_sync.gd",
		"scene_path": "",
		"extends": "Node",
		"category": "Quests",
		"add_mode": "child",
		"description": "Drop one into a level: spawns/removes a WorldMarker for each active quest objective with show_marker.",
		"key_exports": ["marker_color"],
	},
	{
		"class_name": "Grapple",
		"script_path": "res://scripts/components/abilities/grapple.gd",
		"scene_path": "res://scenes/components/abilities/Grapple.tscn",
		"extends": "Ability",
		"category": "Player",
		"add_mode": "instance",
		"description": "Player ability: a grappling hook; presence grants the mechanic. Owns its rope config .tres.",
		"key_exports": ["config", "enabled"],
	},
	{
		"class_name": "WallClimb",
		"script_path": "res://scripts/components/abilities/wall_climb.gd",
		"scene_path": "res://scenes/components/abilities/WallClimb.tscn",
		"extends": "Ability",
		"category": "Player",
		"add_mode": "instance",
		"description": "Player ability: climb/scale walls; presence grants the mechanic. Owns its climb tuning.",
		"key_exports": ["wall_climb_speed", "wall_grip_stick", "climb_hop_up", "climb_hop_forward", "enabled"],
	},
	{
		"class_name": "Slide",
		"script_path": "res://scripts/components/abilities/slide.gd",
		"scene_path": "res://scenes/components/abilities/Slide.tscn",
		"extends": "Ability",
		"category": "Player",
		"add_mode": "instance",
		"description": "Player ability: a momentum slide; presence grants the mechanic, with slide-speed/friction/boost tuning.",
		"key_exports": ["slide_min_speed", "slide_friction", "slide_max_speed", "slide_boost", "slide_sound"],
	},
	{
		"class_name": "AirDash",
		"script_path": "res://scripts/components/abilities/air_dash.gd",
		"scene_path": "res://scenes/components/abilities/AirDash.tscn",
		"extends": "Ability",
		"category": "Player",
		"add_mode": "instance",
		"description": "Player ability: a mid-air dash; presence grants the mechanic.",
		"key_exports": ["enabled"],
	},
	{
		"class_name": "LaserSight",
		"script_path": "res://scripts/components/abilities/laser_sight.gd",
		"scene_path": "res://scenes/components/abilities/LaserSight.tscn",
		"extends": "Ability",
		"category": "Player",
		"add_mode": "instance",
		"description": "Player ability: a weapon laser sight; presence grants the mechanic.",
		"key_exports": ["enabled"],
	},
	{
		"class_name": "SkyTitle",
		"script_path": "res://scripts/components/sky_title.gd",
		"scene_path": "res://scenes/components/sky_title.tscn",
		"extends": "Node3D",
		"category": "Effects",
		"add_mode": "instance",
		"description": "A depth-tested drawn-in-the-sky title card that the skyline occludes; fades in on a music cue. Drop one under the Game root.",
		"key_exports": ["text", "cue_seconds", "fade_in_time", "hold_seconds", "fade_out_time"],
	},
	{
		"class_name": "AmbientDust",
		"script_path": "res://scripts/components/ambient_dust.gd",
		"scene_path": "res://scenes/components/ambient_dust.tscn",
		"extends": "GPUParticles3D",
		"category": "Effects",
		"add_mode": "instance",
		"description": "Level-wide floating motes that re-centre on the camera; drop one anywhere.",
		"key_exports": ["motes", "mote_lifetime", "volume_extents", "mote_size", "mote_color"],
	},
	{
		"class_name": "AmbientSound",
		"script_path": "res://scripts/components/ambient_sound.gd",
		"scene_path": "",
		"extends": "Node3D",
		"category": "Audio",
		"add_mode": "child",
		"description": "A looping ambient bed (wind, hum, crowd); auto-creates a child AudioStreamPlayer3D on the ambient bus.",
		"key_exports": ["stream", "volume_db", "bus", "loop", "autoplay"],
	},
	{
		"class_name": "AudioZone",
		"script_path": "res://scripts/components/audio_zone.gd",
		"scene_path": "",
		"extends": "Area3D",
		"category": "Audio",
		"add_mode": "child",
		"description": "While the player is inside, a child sound cross-fades in; on exit it fades back out (a bar's music, a PA loop).",
		"key_exports": ["trigger_group", "active_volume_db", "inactive_volume_db", "fade_speed", "autoplay"],
	},
	{
		"class_name": "MusicDirector",
		"script_path": "res://scripts/components/music_director.gd",
		"scene_path": "res://scenes/components/music_director.tscn",
		"extends": "Node",
		"category": "Audio",
		"add_mode": "instance",
		"description": "Dynamic music: drop as a child of a music AudioStreamPlayer; the track stays silent in exploration, fading in during combat/dialogue.",
		"key_exports": ["fade_in_time", "fade_out_time", "combat_linger", "silent_db"],
	},
	{
		"class_name": "RentCollector",
		"script_path": "res://scripts/components/rent_collector.gd",
		"scene_path": "",
		"extends": "Node",
		"category": "World Objects",
		"add_mode": "child",
		"description": "Charges the player periodic rent (a property/upkeep cost) every period_days, with paid/missed messages.",
		"key_exports": ["rent_amount", "period_days", "paid_message", "missed_message"],
	},
	{
		"class_name": "NavBlocker",
		"script_path": "res://scripts/components/nav_blocker.gd",
		"scene_path": "",
		"extends": "NavigationObstacle3D",
		"category": "Level",
		"add_mode": "child",
		"description": "Child a solid prop (CARVE) or movable (AVOID) to keep NPC navmesh paths off it; re-bake after CARVE changes.",
		"key_exports": ["mode", "size_override"],
	},
	{
		"class_name": "NavDebugOverlay",
		"script_path": "res://scripts/components/nav_debug_overlay.gd",
		"scene_path": "",
		"extends": "Node",
		"category": "Level",
		"add_mode": "child",
		"description": "A debug overlay that draws NPC navigation paths/agent lines; toggle in inspector or via an input action.",
		"key_exports": ["enabled", "toggle_action", "agent_paths"],
	},
	{
		"class_name": "GameRoot",
		"script_path": "res://scripts/world/game_root.gd",
		"scene_path": "",
		"extends": "Node3D",
		"category": "Level",
		"add_mode": "child",
		"description": "The top-level game controller that owns level loading (load_level) and player placement; one per game scene.",
		"key_exports": [],
	},
	{
		"class_name": "LevelRoot",
		"script_path": "res://scripts/world/level_root.gd",
		"scene_path": "",
		"extends": "Node3D",
		"category": "Level",
		"add_mode": "child",
		"description": "The root of a level; an @tool validator that warns on missing/duplicate PlayerSpawns and bad navmesh bakes.",
		"key_exports": [],
	},
	{
		"class_name": "Ragdoll",
		"script_path": "res://scripts/components/ragdoll.gd",
		"scene_path": "",
		"extends": "Node3D",
		"category": "NPC",
		"add_mode": "child",
		"description": "Physics-skeleton ragdoll for a dead NPC; needs one-time editor setup then assigned to the enemy's ragdoll_scene.",
		"key_exports": ["lifetime", "fade_time", "fade_speed", "outline_color", "outline_width"],
	},
	{
		"class_name": "Readable",
		"script_path": "res://scripts/components/readable.gd",
		"scene_path": "",
		"extends": "LookAtInteractable",
		"category": "World Objects",
		"add_mode": "child",
		"description": "Aim+E to read an authored note/terminal; can set a story flag, advance a quest objective, and grant XP on first read.",
		"key_exports": ["title", "verb", "set_flag_on_read", "advance_quest_id", "advance_objective_id", "xp_on_read"],
	},
	{
		"class_name": "Switch",
		"script_path": "res://scripts/components/switch_lever.gd",
		"scene_path": "",
		"extends": "LookAtInteractable",
		"category": "World Objects",
		"add_mode": "child",
		"description": "Aim+E lever/button: runs an action on a target NodePath, can set a story flag, toast, and play a sound. one_shot for a single use.",
		"key_exports": ["verb", "one_shot", "set_flag", "action", "target", "toast_text"],
	},
	{
		"class_name": "Claimable",
		"script_path": "res://scripts/components/claimable.gd",
		"scene_path": "",
		"extends": "Area3D",
		"category": "World Objects",
		"add_mode": "child",
		"description": "Aim+hold to befriend/claim an NPC or object (optionally name it); toggles a claimed outline and can allow un-claiming.",
		"key_exports": ["enabled", "prompt_verb", "display_name", "ask_for_name", "show_claimed_outline", "allow_unclaim"],
	},
	{
		"class_name": "FallImmunity",
		"script_path": "res://scripts/components/abilities/fall_immunity.gd",
		"scene_path": "res://scenes/components/abilities/FallImmunity.tscn",
		"extends": "Ability",
		"category": "Player",
		"add_mode": "instance",
		"description": "A passive UPGRADE ability: while present + enabled on the Player, a hard landing costs no HP. Grant via an UpgradePickup (drag FallImmunity.tscn into its grants).",
		"key_exports": ["enabled"],
	},
]
